### PR TITLE
Update imgui_node_editor.cpp

### PR DESCRIPTION
**Pull request by lance5**
[fix] IM_ASSERT(size_arg.x != 0.0f && size_arg.y != 0.0f);

### CODE REVIEW

**Comment by tianyu2** [comment]
Thank you for fixing this issue but I have 1 more question do you have any idea why the node looks like this? 
image

**Comment by tianyu2** [comment]
to be honest i am just porting over the code from the blueprint examples to test on my game engine 
image

**Comment by lance5** [comment]
Maybe you shall use 1.72.

**Comment by thedmd** [comment]
This issue is fixed on `develop`. Please update if possible.

Thanks for your help!

**Pull request closed without merging**
